### PR TITLE
Don't store or delete the cookie if desired

### PR DESCRIPTION
**Pull request by xavijam**
If we don't want to generate the cookie + the uuid, there is a new option called `data-cookie-enabled` when initializing the script.

### CODE REVIEW

**Comment by xavijam** [comment]
Makes sense @ivanmalagon?

**Comment by ivanmalagon** [comment]
👀

**Comment by ivanmalagon** [comment]
This works right if we wait to initialise the script until the user has accepted or rejected the consent. That's how it should be implemented by a client.

But in the case the script is already initialised, since the parameter is read in initialisation, it won't have any effect until the next refresh.

If the library is used as it should be, no problem. If we want to cover more bases, we should expose another function to be called to delete the cookie.

**Comment by xavijam** [comment]
> But in the case the script is already initialised, since the parameter is read in initialisation, it won't have any effect until the next refresh.

Yes, I want to cover the easy one before doing it more complex

**Pull request merged**
